### ISSUE TITLE
Remote iCloud files don't show up

### ISSUE THREAD

**Issue by normen** [holzschu/a-Shell_iOS#1]
Hi,

first of all thank you very much for this awesome App. I was looking for a VIM editor on iOS and this looks very promising. I tried around with Blink and iVim but encountered various issues (Blink has no local VIM and iVim doesn't support my german keyboard very well yet).

Now I am testing a-Shell and while it looks and works very nice with my keyboard I do seem to have issues with its iCloud/iOS Files support. The problem is that files that are not downloaded to the iPad (cloud icon in the Files app) do not show up in directory listings in a-Shell. When I do a `ls` in a cloud folder all remote files seem to be missing.

As a workaround I can of course download the file in Apples Files app after which they appear in the a-Shell directory listing as well but that is very cumbersome especially with folder structures with many subfolders (e.g. my `.vim` folder).

Thanks for the attention,
Normen Hansen

**Comment by normen** [comment]
Sorry, realizing this is the wrong repo... I'll post in the correct one.

**Comment by holzschu** [comment]
No problems, I didn't even know this repository had an issues tab!
